name: "Github Actions"
run-name: "${{ github.actor }} is testing out Github Actions"

on: [push]

jobs:
  build:
    name: Build Tricking Library App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.1
      - name: Print current directory
        run: pwd
      - name: List files in current directory
        run: ls
      - name: Build server
        run: dotnet build
      - name: List Tricking Library Files
        run: ls TrickingLibrary.api/ -R
      - name: Check pnpm Version
        run: npm -v

    